# KrossIAM Message service Configuration
# https://github.com/krossdev/iam-ms/blob/main/LICENSE

# Debug mode or not
debug: true

# Log parameters
#
log:
  # Where to save log file(it's a path name, not filename)
  #
  path: /tmp

  # Airbrake hook configuration, comment to disable it
  # https://airbrake.io
  #
  # 'pid' is project id, it's a integer number, and 'key' is project key,
  # you can get them from your airbrade account
  #
  airbrake:
    pid: project-id
    key: project-key

# Nats server(s)
#
brokers:
  - nats://localhost:4222

# Mail configuration
#
mail:
  # Add prefix to mail subject
  #
  subject_prefix: '[KrossIAM]'

  # MTAs(mail transfer agent), You can add multiple mta as fallbacks
  #
  mtas:
    -
      # mail service provider name
      name: provider-name
      # smtp host
      host: smtp.host.com
      # smtp port
      port: 465
      # connection mode
      sslmode: true
      # sender address(RFC 5322), can contain display name like 'name <sender@host.com>'
      sender: youname <noreply@host.com>
      # authenticate password
      passwd: password
